let flights = [
    {
      "id": "1",
      "airline": "Delta Air Lines",
      "flightNumber": "DL1234",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "4",
      "departureGate": "B22",
      "departureTime": "10:30",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "5",
      "arrivalGate": "C10",
      "arrivalTime": "13:45",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "2",
      "airline": "United Airlines",
      "flightNumber": "UA5678",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "1",
      "departureGate": "A5",
      "departureTime": "15:00",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "3",
      "arrivalGate": "F12",
      "arrivalTime": "17:30",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "3",
      "airline": "Alaska Airlines",
      "flightNumber": "DL8640",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "1",
      "departureGate": "E9",
      "departureTime": "09:51",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "4",
      "arrivalGate": "D14",
      "arrivalTime": "14:27",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "4",
      "airline": "American Airlines",
      "flightNumber": "AS5612",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "3",
      "departureGate": "C11",
      "departureTime": "09:21",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "3",
      "arrivalGate": "C17",
      "arrivalTime": "11:45",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "5",
      "airline": "Delta Air Lines",
      "flightNumber": "DL412",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "4",
      "departureGate": "C7",
      "departureTime": "15:29",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "2",
      "arrivalGate": "B24",
      "arrivalTime": "17:04",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "6",
      "airline": "American Airlines",
      "flightNumber": "SP3467",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "2",
      "departureGate": "H10",
      "departureTime": "12:07",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "4",
      "arrivalGate": "F10",
      "arrivalTime": "15:42",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "7",
      "airline": "Frontier Airlines",
      "flightNumber": "SP3887",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "5",
      "departureGate": "C1",
      "departureTime": "12:36",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "B21",
      "arrivalTime": "16:42",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "8",
      "airline": "Frontier Airlines",
      "flightNumber": "JB2908",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "3",
      "departureGate": "C3",
      "departureTime": "14:54",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "1",
      "arrivalGate": "B13",
      "arrivalTime": "16:42",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "9",
      "airline": "Southwest",
      "flightNumber": "SP7198",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "2",
      "departureGate": "E7",
      "departureTime": "08:43",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "4",
      "arrivalGate": "D2",
      "arrivalTime": "12:22",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "10",
      "airline": "Southwest",
      "flightNumber": "DL7912",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "3",
      "departureGate": "F21",
      "departureTime": "06:12",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ATL",
      "arrivalCity": "Atlanta",
      "arrivalTerminal": "2",
      "arrivalGate": "C8",
      "arrivalTime": "08:04",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "11",
      "airline": "United Airlines",
      "flightNumber": "SW9658",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "5",
      "departureGate": "B17",
      "departureTime": "15:38",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "5",
      "arrivalGate": "F3",
      "arrivalTime": "18:06",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "12",
      "airline": "Delta Air Lines",
      "flightNumber": "FR2901",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "1",
      "departureGate": "D10",
      "departureTime": "16:21",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "3",
      "arrivalGate": "A19",
      "arrivalTime": "19:20",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "13",
      "airline": "Alaska Airlines",
      "flightNumber": "SW8299",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "2",
      "departureGate": "D16",
      "departureTime": "10:55",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "1",
      "arrivalGate": "A17",
      "arrivalTime": "12:36",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "14",
      "airline": "United Airlines",
      "flightNumber": "FR3855",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "1",
      "departureGate": "F13",
      "departureTime": "21:49",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "3",
      "arrivalGate": "H2",
      "arrivalTime": "23:24",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "15",
      "airline": "JetBlue",
      "flightNumber": "SW9931",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "4",
      "departureGate": "A16",
      "departureTime": "17:50",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "3",
      "arrivalGate": "E21",
      "arrivalTime": "20:14",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "16",
      "airline": "Frontier Airlines",
      "flightNumber": "UA3944",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "1",
      "departureGate": "A5",
      "departureTime": "18:02",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "2",
      "arrivalGate": "H24",
      "arrivalTime": "20:18",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "17",
      "airline": "United Airlines",
      "flightNumber": "SW5879",
      "departureAirport": "BOS",
      "departureCity": "Boston",
      "departureTerminal": "5",
      "departureGate": "H6",
      "departureTime": "21:29",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "3",
      "arrivalGate": "A5",
      "arrivalTime": "02:24",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "18",
      "airline": "Alaska Airlines",
      "flightNumber": "SW3075",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "2",
      "departureGate": "C24",
      "departureTime": "21:33",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "3",
      "arrivalGate": "A20",
      "arrivalTime": "23:44",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "19",
      "airline": "American Airlines",
      "flightNumber": "SP6241",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "5",
      "departureGate": "C7",
      "departureTime": "07:45",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "3",
      "arrivalGate": "C15",
      "arrivalTime": "09:58",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "20",
      "airline": "American Airlines",
      "flightNumber": "DL6249",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "4",
      "departureGate": "B13",
      "departureTime": "11:19",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "5",
      "arrivalGate": "C17",
      "arrivalTime": "15:30",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "21",
      "airline": "Frontier Airlines",
      "flightNumber": "UA2316",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "4",
      "departureGate": "G4",
      "departureTime": "19:58",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "3",
      "arrivalGate": "D24",
      "arrivalTime": "23:20",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "22",
      "airline": "Alaska Airlines",
      "flightNumber": "SP1414",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "3",
      "departureGate": "H22",
      "departureTime": "20:29",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "H11",
      "arrivalTime": "22:44",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "23",
      "airline": "Southwest",
      "flightNumber": "DL3209",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "3",
      "departureGate": "H1",
      "departureTime": "18:58",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "1",
      "arrivalGate": "H23",
      "arrivalTime": "22:50",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "24",
      "airline": "Southwest",
      "flightNumber": "SW3865",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "2",
      "departureGate": "G18",
      "departureTime": "16:08",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "2",
      "arrivalGate": "F4",
      "arrivalTime": "19:48",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "25",
      "airline": "American Airlines",
      "flightNumber": "SP3625",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "5",
      "departureGate": "H16",
      "departureTime": "19:58",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "1",
      "arrivalGate": "C21",
      "arrivalTime": "21:43",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "26",
      "airline": "Alaska Airlines",
      "flightNumber": "UA5177",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "3",
      "departureGate": "B16",
      "departureTime": "16:43",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "1",
      "arrivalGate": "A8",
      "arrivalTime": "20:37",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "27",
      "airline": "Southwest",
      "flightNumber": "DL4914",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "4",
      "departureGate": "B11",
      "departureTime": "14:45",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "4",
      "arrivalGate": "B23",
      "arrivalTime": "16:43",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "28",
      "airline": "Delta Air Lines",
      "flightNumber": "DL2360",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "4",
      "departureGate": "G19",
      "departureTime": "20:07",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "2",
      "arrivalGate": "C18",
      "arrivalTime": "23:16",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "29",
      "airline": "United Airlines",
      "flightNumber": "AA2340",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "1",
      "departureGate": "B4",
      "departureTime": "15:22",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "4",
      "arrivalGate": "D15",
      "arrivalTime": "17:02",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "30",
      "airline": "Spirit Airlines",
      "flightNumber": "SP6741",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "3",
      "departureGate": "D20",
      "departureTime": "19:51",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "2",
      "arrivalGate": "A24",
      "arrivalTime": "22:18",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "31",
      "airline": "American Airlines",
      "flightNumber": "AS6963",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "2",
      "departureGate": "D15",
      "departureTime": "14:31",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "1",
      "arrivalGate": "E16",
      "arrivalTime": "17:13",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "32",
      "airline": "Delta Air Lines",
      "flightNumber": "UA2127",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "5",
      "departureGate": "D10",
      "departureTime": "11:09",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "2",
      "arrivalGate": "B3",
      "arrivalTime": "14:13",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "33",
      "airline": "JetBlue",
      "flightNumber": "FR8512",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "4",
      "departureGate": "F4",
      "departureTime": "10:35",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "1",
      "arrivalGate": "A17",
      "arrivalTime": "14:10",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "34",
      "airline": "Spirit Airlines",
      "flightNumber": "JB4728",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "1",
      "departureGate": "C23",
      "departureTime": "19:11",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "2",
      "arrivalGate": "F8",
      "arrivalTime": "21:12",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "35",
      "airline": "JetBlue",
      "flightNumber": "FR7498",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "4",
      "departureGate": "F9",
      "departureTime": "21:01",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "5",
      "arrivalGate": "F23",
      "arrivalTime": "23:27",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "36",
      "airline": "Spirit Airlines",
      "flightNumber": "UA6925",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "4",
      "departureGate": "G10",
      "departureTime": "10:58",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "5",
      "arrivalGate": "F12",
      "arrivalTime": "13:11",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "37",
      "airline": "Frontier Airlines",
      "flightNumber": "DL1729",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "3",
      "departureGate": "E15",
      "departureTime": "07:45",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "5",
      "arrivalGate": "B11",
      "arrivalTime": "10:38",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "38",
      "airline": "Spirit Airlines",
      "flightNumber": "JB4015",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "2",
      "departureGate": "E19",
      "departureTime": "17:26",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "2",
      "arrivalGate": "H8",
      "arrivalTime": "20:58",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "39",
      "airline": "Alaska Airlines",
      "flightNumber": "JB6746",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "2",
      "departureGate": "G8",
      "departureTime": "14:56",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ATL",
      "arrivalCity": "Atlanta",
      "arrivalTerminal": "1",
      "arrivalGate": "F9",
      "arrivalTime": "18:07",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "40",
      "airline": "American Airlines",
      "flightNumber": "AS5406",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "1",
      "departureGate": "E20",
      "departureTime": "18:55",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "2",
      "arrivalGate": "H17",
      "arrivalTime": "20:56",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "41",
      "airline": "United Airlines",
      "flightNumber": "AA2068",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "2",
      "departureGate": "C13",
      "departureTime": "07:27",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ATL",
      "arrivalCity": "Atlanta",
      "arrivalTerminal": "1",
      "arrivalGate": "E15",
      "arrivalTime": "11:56",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "42",
      "airline": "Delta Air Lines",
      "flightNumber": "SP5556",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "1",
      "departureGate": "C17",
      "departureTime": "14:32",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "2",
      "arrivalGate": "H12",
      "arrivalTime": "19:26",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "43",
      "airline": "Spirit Airlines",
      "flightNumber": "UA2857",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "2",
      "departureGate": "F3",
      "departureTime": "17:00",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "1",
      "arrivalGate": "D24",
      "arrivalTime": "20:04",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "44",
      "airline": "Alaska Airlines",
      "flightNumber": "JB9908",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "5",
      "departureGate": "E6",
      "departureTime": "16:29",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "3",
      "arrivalGate": "F24",
      "arrivalTime": "18:45",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "45",
      "airline": "American Airlines",
      "flightNumber": "JB3326",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "3",
      "departureGate": "B10",
      "departureTime": "12:55",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "2",
      "arrivalGate": "B6",
      "arrivalTime": "17:53",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "46",
      "airline": "Delta Air Lines",
      "flightNumber": "AA7314",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "5",
      "departureGate": "B24",
      "departureTime": "11:04",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "3",
      "arrivalGate": "H10",
      "arrivalTime": "12:41",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "47",
      "airline": "Delta Air Lines",
      "flightNumber": "AS5632",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "1",
      "departureGate": "F24",
      "departureTime": "15:28",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "4",
      "arrivalGate": "C7",
      "arrivalTime": "20:16",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "48",
      "airline": "Frontier Airlines",
      "flightNumber": "SW4488",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "1",
      "departureGate": "F14",
      "departureTime": "12:37",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "H18",
      "arrivalTime": "14:13",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "49",
      "airline": "Delta Air Lines",
      "flightNumber": "AS3343",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "2",
      "departureGate": "A9",
      "departureTime": "14:32",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "1",
      "arrivalGate": "F6",
      "arrivalTime": "16:31",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "50",
      "airline": "Frontier Airlines",
      "flightNumber": "AA2066",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "2",
      "departureGate": "E10",
      "departureTime": "21:45",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "3",
      "arrivalGate": "A9",
      "arrivalTime": "01:12",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "51",
      "airline": "Frontier Airlines",
      "flightNumber": "SP2889",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "2",
      "departureGate": "A14",
      "departureTime": "11:13",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "4",
      "arrivalGate": "D8",
      "arrivalTime": "14:40",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "52",
      "airline": "Frontier Airlines",
      "flightNumber": "UA383",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "4",
      "departureGate": "G24",
      "departureTime": "13:41",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "4",
      "arrivalGate": "A1",
      "arrivalTime": "18:30",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "53",
      "airline": "Southwest",
      "flightNumber": "SW4878",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "4",
      "departureGate": "C1",
      "departureTime": "07:52",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "3",
      "arrivalGate": "C12",
      "arrivalTime": "11:20",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "54",
      "airline": "Frontier Airlines",
      "flightNumber": "SW5488",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "5",
      "departureGate": "B18",
      "departureTime": "13:41",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "1",
      "arrivalGate": "A2",
      "arrivalTime": "16:04",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "55",
      "airline": "American Airlines",
      "flightNumber": "SP7436",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "1",
      "departureGate": "B2",
      "departureTime": "14:18",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "4",
      "arrivalGate": "H21",
      "arrivalTime": "18:21",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "56",
      "airline": "Spirit Airlines",
      "flightNumber": "FR288",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "3",
      "departureGate": "C7",
      "departureTime": "09:40",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "5",
      "arrivalGate": "E20",
      "arrivalTime": "11:30",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "57",
      "airline": "Southwest",
      "flightNumber": "SP2707",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "1",
      "departureGate": "B18",
      "departureTime": "07:44",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "4",
      "arrivalGate": "C14",
      "arrivalTime": "09:34",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "58",
      "airline": "Frontier Airlines",
      "flightNumber": "DL9382",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "3",
      "departureGate": "H4",
      "departureTime": "08:15",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "2",
      "arrivalGate": "F1",
      "arrivalTime": "10:03",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "59",
      "airline": "American Airlines",
      "flightNumber": "JB2067",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "1",
      "departureGate": "G18",
      "departureTime": "15:18",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "4",
      "arrivalGate": "G13",
      "arrivalTime": "18:31",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "60",
      "airline": "Delta Air Lines",
      "flightNumber": "DL6845",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "2",
      "departureGate": "E13",
      "departureTime": "11:15",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "4",
      "arrivalGate": "H23",
      "arrivalTime": "15:26",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "61",
      "airline": "JetBlue",
      "flightNumber": "FR1479",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "1",
      "departureGate": "G9",
      "departureTime": "09:10",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "3",
      "arrivalGate": "G18",
      "arrivalTime": "12:56",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "62",
      "airline": "Alaska Airlines",
      "flightNumber": "JB6289",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "3",
      "departureGate": "G16",
      "departureTime": "17:26",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "4",
      "arrivalGate": "G11",
      "arrivalTime": "19:15",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "63",
      "airline": "Frontier Airlines",
      "flightNumber": "AS2232",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "3",
      "departureGate": "B24",
      "departureTime": "17:36",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "G20",
      "arrivalTime": "19:25",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "64",
      "airline": "United Airlines",
      "flightNumber": "AA2326",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "1",
      "departureGate": "H12",
      "departureTime": "18:07",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "1",
      "arrivalGate": "F5",
      "arrivalTime": "21:22",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "65",
      "airline": "Delta Air Lines",
      "flightNumber": "AS4396",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "3",
      "departureGate": "A24",
      "departureTime": "07:30",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "3",
      "arrivalGate": "F13",
      "arrivalTime": "10:19",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "66",
      "airline": "Spirit Airlines",
      "flightNumber": "SW6773",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "3",
      "departureGate": "C17",
      "departureTime": "21:09",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "1",
      "arrivalGate": "E7",
      "arrivalTime": "23:00",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "67",
      "airline": "United Airlines",
      "flightNumber": "AS8397",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "4",
      "departureGate": "E8",
      "departureTime": "07:52",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "4",
      "arrivalGate": "B21",
      "arrivalTime": "12:05",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "68",
      "airline": "Delta Air Lines",
      "flightNumber": "SW6404",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "4",
      "departureGate": "A5",
      "departureTime": "11:43",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "1",
      "arrivalGate": "B17",
      "arrivalTime": "14:29",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "69",
      "airline": "Alaska Airlines",
      "flightNumber": "UA4410",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "4",
      "departureGate": "G7",
      "departureTime": "17:59",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "4",
      "arrivalGate": "D4",
      "arrivalTime": "22:06",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "70",
      "airline": "Frontier Airlines",
      "flightNumber": "UA3728",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "3",
      "departureGate": "D8",
      "departureTime": "06:28",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "5",
      "arrivalGate": "A16",
      "arrivalTime": "10:36",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "71",
      "airline": "Southwest",
      "flightNumber": "SW4537",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "4",
      "departureGate": "D10",
      "departureTime": "09:13",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ATL",
      "arrivalCity": "Atlanta",
      "arrivalTerminal": "5",
      "arrivalGate": "B20",
      "arrivalTime": "13:30",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "72",
      "airline": "Spirit Airlines",
      "flightNumber": "AS4692",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "3",
      "departureGate": "C8",
      "departureTime": "08:22",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "1",
      "arrivalGate": "B3",
      "arrivalTime": "11:17",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "73",
      "airline": "United Airlines",
      "flightNumber": "AS8385",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "4",
      "departureGate": "D10",
      "departureTime": "08:12",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "3",
      "arrivalGate": "D10",
      "arrivalTime": "11:52",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "74",
      "airline": "Delta Air Lines",
      "flightNumber": "AA6325",
      "departureAirport": "SFO",
      "departureCity": "San Francisco",
      "departureTerminal": "5",
      "departureGate": "B19",
      "departureTime": "15:39",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "4",
      "arrivalGate": "A17",
      "arrivalTime": "18:58",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "75",
      "airline": "Alaska Airlines",
      "flightNumber": "UA3668",
      "departureAirport": "BOS",
      "departureCity": "Boston",
      "departureTerminal": "4",
      "departureGate": "F14",
      "departureTime": "21:45",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "4",
      "arrivalGate": "E20",
      "arrivalTime": "02:44",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "76",
      "airline": "JetBlue",
      "flightNumber": "FR6697",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "1",
      "departureGate": "F24",
      "departureTime": "06:47",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "2",
      "arrivalGate": "C23",
      "arrivalTime": "11:13",
      "arrivalDate": "2024-07-22",
      "status": "Delayed"
    },
    {
      "id": "77",
      "airline": "Delta Air Lines",
      "flightNumber": "AA3653",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "4",
      "departureGate": "F14",
      "departureTime": "11:52",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "1",
      "arrivalGate": "C2",
      "arrivalTime": "14:14",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "78",
      "airline": "American Airlines",
      "flightNumber": "UA8025",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "5",
      "departureGate": "D13",
      "departureTime": "07:57",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "1",
      "arrivalGate": "E22",
      "arrivalTime": "11:19",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "79",
      "airline": "United Airlines",
      "flightNumber": "AS7026",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "5",
      "departureGate": "B13",
      "departureTime": "19:15",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "G21",
      "arrivalTime": "23:37",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "80",
      "airline": "Alaska Airlines",
      "flightNumber": "JB7183",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "5",
      "departureGate": "A22",
      "departureTime": "21:54",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "4",
      "arrivalGate": "C3",
      "arrivalTime": "00:29",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "81",
      "airline": "JetBlue",
      "flightNumber": "UA7781",
      "departureAirport": "SEA",
      "departureCity": "Seattle",
      "departureTerminal": "1",
      "departureGate": "D12",
      "departureTime": "13:47",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "2",
      "arrivalGate": "E14",
      "arrivalTime": "18:15",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "82",
      "airline": "Alaska Airlines",
      "flightNumber": "DL6980",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "1",
      "departureGate": "D17",
      "departureTime": "10:40",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DEN",
      "arrivalCity": "Denver",
      "arrivalTerminal": "4",
      "arrivalGate": "G23",
      "arrivalTime": "14:10",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "83",
      "airline": "JetBlue",
      "flightNumber": "SW8424",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "3",
      "departureGate": "A3",
      "departureTime": "14:21",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SEA",
      "arrivalCity": "Seattle",
      "arrivalTerminal": "4",
      "arrivalGate": "B21",
      "arrivalTime": "16:11",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "84",
      "airline": "Alaska Airlines",
      "flightNumber": "JB1493",
      "departureAirport": "BOS",
      "departureCity": "Boston",
      "departureTerminal": "2",
      "departureGate": "F16",
      "departureTime": "12:24",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "4",
      "arrivalGate": "H24",
      "arrivalTime": "14:48",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "85",
      "airline": "United Airlines",
      "flightNumber": "SW8160",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "2",
      "departureGate": "B4",
      "departureTime": "21:55",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "C18",
      "arrivalTime": "23:49",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "86",
      "airline": "Alaska Airlines",
      "flightNumber": "FR2114",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "5",
      "departureGate": "A11",
      "departureTime": "09:50",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "3",
      "arrivalGate": "D2",
      "arrivalTime": "12:07",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "87",
      "airline": "Spirit Airlines",
      "flightNumber": "AS3455",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "2",
      "departureGate": "F16",
      "departureTime": "19:03",
      "departureDate": "2024-07-22",
      "arrivalAirport": "ORD",
      "arrivalCity": "Chicago",
      "arrivalTerminal": "5",
      "arrivalGate": "H15",
      "arrivalTime": "23:10",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "88",
      "airline": "American Airlines",
      "flightNumber": "DL3229",
      "departureAirport": "BOS",
      "departureCity": "Boston",
      "departureTerminal": "4",
      "departureGate": "E7",
      "departureTime": "21:45",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "2",
      "arrivalGate": "E20",
      "arrivalTime": "02:37",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "89",
      "airline": "JetBlue",
      "flightNumber": "AA1023",
      "departureAirport": "LAX",
      "departureCity": "Los Angeles",
      "departureTerminal": "4",
      "departureGate": "E12",
      "departureTime": "07:51",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "5",
      "arrivalGate": "H11",
      "arrivalTime": "10:59",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "90",
      "airline": "Delta Air Lines",
      "flightNumber": "JB3418",
      "departureAirport": "BOS",
      "departureCity": "Boston",
      "departureTerminal": "3",
      "departureGate": "C18",
      "departureTime": "07:00",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "5",
      "arrivalGate": "D2",
      "arrivalTime": "11:12",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "91",
      "airline": "JetBlue",
      "flightNumber": "DL3970",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "1",
      "departureGate": "C22",
      "departureTime": "09:40",
      "departureDate": "2024-07-22",
      "arrivalAirport": "JFK",
      "arrivalCity": "New York",
      "arrivalTerminal": "2",
      "arrivalGate": "F1",
      "arrivalTime": "11:42",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "92",
      "airline": "American Airlines",
      "flightNumber": "AA3454",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "3",
      "departureGate": "E7",
      "departureTime": "06:53",
      "departureDate": "2024-07-22",
      "arrivalAirport": "MIA",
      "arrivalCity": "Miami",
      "arrivalTerminal": "5",
      "arrivalGate": "G5",
      "arrivalTime": "09:17",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "93",
      "airline": "American Airlines",
      "flightNumber": "FR9444",
      "departureAirport": "ATL",
      "departureCity": "Atlanta",
      "departureTerminal": "1",
      "departureGate": "G22",
      "departureTime": "20:26",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "4",
      "arrivalGate": "E18",
      "arrivalTime": "01:11",
      "arrivalDate": "2024-07-22",
      "status": "On Time"
    },
    {
      "id": "94",
      "airline": "United Airlines",
      "flightNumber": "SP6053",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "4",
      "departureGate": "E22",
      "departureTime": "06:25",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "5",
      "arrivalGate": "C9",
      "arrivalTime": "11:24",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    },
    {
      "id": "95",
      "airline": "JetBlue",
      "flightNumber": "UA8743",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "5",
      "departureGate": "A19",
      "departureTime": "07:35",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "4",
      "arrivalGate": "G9",
      "arrivalTime": "09:49",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "96",
      "airline": "Frontier Airlines",
      "flightNumber": "JB1071",
      "departureAirport": "ORD",
      "departureCity": "Chicago",
      "departureTerminal": "4",
      "departureGate": "C17",
      "departureTime": "15:19",
      "departureDate": "2024-07-22",
      "arrivalAirport": "LAX",
      "arrivalCity": "Los Angeles",
      "arrivalTerminal": "4",
      "arrivalGate": "D2",
      "arrivalTime": "17:46",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "97",
      "airline": "Frontier Airlines",
      "flightNumber": "UA4975",
      "departureAirport": "DFW",
      "departureCity": "Dallas",
      "departureTerminal": "1",
      "departureGate": "A8",
      "departureTime": "13:31",
      "departureDate": "2024-07-22",
      "arrivalAirport": "BOS",
      "arrivalCity": "Boston",
      "arrivalTerminal": "5",
      "arrivalGate": "A8",
      "arrivalTime": "16:11",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "98",
      "airline": "Spirit Airlines",
      "flightNumber": "AS5525",
      "departureAirport": "MIA",
      "departureCity": "Miami",
      "departureTerminal": "5",
      "departureGate": "E4",
      "departureTime": "12:21",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "4",
      "arrivalGate": "B13",
      "arrivalTime": "17:10",
      "arrivalDate": "2024-07-22",
      "status": "Boarding"
    },
    {
      "id": "99",
      "airline": "Spirit Airlines",
      "flightNumber": "SW9690",
      "departureAirport": "JFK",
      "departureCity": "New York",
      "departureTerminal": "2",
      "departureGate": "B18",
      "departureTime": "08:06",
      "departureDate": "2024-07-22",
      "arrivalAirport": "DFW",
      "arrivalCity": "Dallas",
      "arrivalTerminal": "3",
      "arrivalGate": "D20",
      "arrivalTime": "11:06",
      "arrivalDate": "2024-07-22",
      "status": "Departed"
    },
    {
      "id": "100",
      "airline": "Delta Air Lines",
      "flightNumber": "DL777",
      "departureAirport": "DEN",
      "departureCity": "Denver",
      "departureTerminal": "5",
      "departureGate": "H17",
      "departureTime": "18:39",
      "departureDate": "2024-07-22",
      "arrivalAirport": "SFO",
      "arrivalCity": "San Francisco",
      "arrivalTerminal": "2",
      "arrivalGate": "C9",
      "arrivalTime": "22:53",
      "arrivalDate": "2024-07-22",
      "status": "Cancelled"
    }
]

export default function handler(req, res) {
  if (req.method === 'GET') {
    res.status(200).json(flights);
  } else if (req.method === 'POST') {
    const newFlight = { id: String(Date.now()), ...req.body };
    flights.push(newFlight);
    res.status(201).json(newFlight);
  } else {
    res.status(405).json({ error: 'Method not allowed' });
  }
} 